---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distnode-auth-deployment
  labels:
    app: distnode-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distnode-auth
  template:
    metadata:
      labels:
        app: distnode-auth
    spec:
      containers:
      - name: distnode-auth
        image: distnode/auth:latest
        imagePullPolicy: Never
        env:
            - name: JWT_ACCESS_TOKEN_SECRET
              value: super-secret-key-1
            - name: JWT_REFRESH_TOKEN_SECRET
              value: super-secret-key-2
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/test
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: distnode-auth-service
  labels:
    app: distnode-auth
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: distnode-auth
